name: Risk29 Daily Morning Report

on:
  schedule:
    # Run at 8:00 AM GMT+7 (1:00 AM UTC) every day
    - cron: '0 1 * * *'
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Send daily report to LINE
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: |
          python send_daily_report.py
